### ISSUE TITLE
Rewrite in golang

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/cf-table#1]
:trollface:

**Comment by drnic** [comment]
Super handy tool btw

**Comment by jhunt** [comment]
:+1:

**Comment by lnguyen** [comment]
:+1:

**Comment by shinji62** [comment]
:+1:

**Comment by ArthurHlt** [comment]
It's a really nice work.
I agree with them and you could rewrite it as a cli plugin in same time, it could be easier to install it.
some links:
- simple plugin example: https://github.com/cloudfoundry/cli/blob/master/plugin_examples/basic_plugin.go
- with call to cli: https://github.com/cloudfoundry/cli/blob/master/plugin_examples/call_cli_cmd/main/call_cli_cmd.go (you can call `cf curl` like this by using `cliConnection.CliCommand('curl', args[1:]...)` )

**Comment by rkoster** [comment]
Will consider rewriting it, I just wanted to validate the usefulness before spending to much time.

**Comment by cxhercules** [comment]
👍

**Comment by drnic** [comment]
Closing.

Anyone using cf-table? I'd forgotten about it until I went on my cleaning spree.

**Comment by rkoster** [comment]
I'd forgotten about it as well, but it seems to be really well written 😄
