### ISSUE TITLE
cf curl /v2/services | cf-table label tags provider - not working

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/cf-table#3]
```
cf curl /v2/services | cf-table
...
cf curl /v2/services | cf-table label tags provider
```

The latter doesn't show the data; it asks for columns again.

**Comment by drnic** [comment]
The `tags` field is causing problems I think.

**Comment by rkoster** [comment]
Encountered this my self as well, will investigate.

**Comment by rkoster** [comment]
Fixed in https://github.com/cloudfoundry-community/cf-table/commit/45c1acd2cdb0f743a8ae40d5754b00340a382a00
